### ISSUE TITLE
[suggestion] horizontal and upwards block breaking

### ISSUE THREAD

**Issue by krispyking24** [bunnyi116/fabric-bedrock-miner#23]
to basically be able to break the block from a different side of the block this could be done by checking the side which the player hits the block on then checks for enough space as on some servers they don't allow placing blocks through something else for example the nether roof

**Comment by Bunnui** [comment]
在新的版本中我加入了不同方向方案的解决方法，只要你不禁用它，它会自己尝试其他方案。

关于旧版本支持问题，由于我工作比较忙，所以不准备对低版本进行支持。

关于检查玩家击中方块的一侧，是可以实现的，但需要等我闲下来的时候在处理。


In the new version, I have added solutions for different directional schemes. As long as you don't disable it, it will automatically attempt other solutions.

Regarding support for the old version, due to my busy schedule, I do not plan to provide support for older versions.

As for checking which side the player hits the block, it is achievable, but it will have to wait until I have some free time to address it.

**Comment by krispyking24** [comment]
> Regarding support for the old version, due to my busy schedule, I do not plan to provide support for older versions.

where did i mention an old version?

**Comment by Bunnui** [comment]
First of all, I'm very sorry, because I can't speak English, so I used the translation tool, I may have misunderstood your meaning.

I'm aware of the request to use the player's tapping surface as the preferred option.

"On some servers, they don't allow placing blocks through other objects, such as the Nether roof."

What does this passage mean? Are some servers not allowed to place pistons on the Nether roof?

**Comment by Bunnui** [comment]
Which means that some servers do not allow other blocks to be placed on top of a certain block? If that's the case, I can try developing and using players to tap on the side of the block, or using commands to configure it.

**Comment by Bunnui** [comment]
I'm ready to rest. I have to work tomorrow.
Note: I may not have that much time for development, as programming is just one of my hobbies and I can only wait for my leisure time to develop.

**Comment by krispyking24** [comment]
closing this as its kind of implemented watch the video, i say kind of as even if u dont have real access to the top of the block it still does the actions there

https://github.com/user-attachments/assets/2e62e298-0ad7-4b64-adc3-df7b2e5cecb4
