### ISSUE TITLE
A little bit slow

### ISSUE THREAD

**Issue by Shakakakaka** [bunnyi116/fabric-bedrock-miner#39]
The mod works well and breaks the bedrock yet it is very slow. it takes about 2 seconds to break 1 bedrock. I am wondering if this is intended or if there is any way to speed it up. The server is at 20tps and the version is 1.20.1

**Comment by bunnyi116** [comment]
在 1.21 版本中，Minecraft 更改了与附魔相关的代码，这导致在切换到指定工具时，附魔不会在同一个 TICK 内生效（前一项的附魔仍然适用）。由于此问题，在任务执行期间无法立即破坏活塞块，从而导致任务失败。因此，我进行了调整以确保任务的执行顺序。

ChatGpt translation:
In version 1.21, Minecraft changed the enchantment-related code, which caused enchantments not to take effect within the same TICK when switching to a specified tool (the enchantments from the previous item are still applied). Because of this issue, it was not possible to instantly break piston blocks during task execution, leading to task failures. Therefore, I made adjustments to ensure the execution order of tasks.
